version: '3.4'

services:
  
  qfileserverdb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - SA_PASSWORD=yourStrong!Passw0rd
      - ACCEPT_EULA=Y
    volumes:
      - C:\Users\dmarra\Desktop\FFMpegUIDemo\QFileServerSqlData:/var/opt/mssql/data

  qfileserver:
    image: "demetriomarra3/qfileserver"
    #command: ["./dockerize", "-wait", "tcp://qfileserverdb:1433", "-timeout", "60s"]
    environment:
      - ConnectionStrings__DefaultConnectionString=Server=qfileserverdb;Initial Catalog=QFileServer;Persist Security Info=False;User ID=sa;Password=yourStrong!Passw0rd;
      - QFileServiceConfiguration__FileServerRootPath=/app/nasroot
    depends_on:
      - qfileserverdb
    volumes:
      - C:\Users\dmarra\Desktop\FFMpegUIDemo\QFileServerNas:/app/nasroot
 
  ffmpeguisql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - SA_PASSWORD=yourStrong!Passw0rd
      - ACCEPT_EULA=Y
    volumes:
      - C:\Users\dmarra\Desktop\FFMpegUIDemo\FFMpegUISqlData:/var/opt/mssql/data
  
  ffmpeguinosql:
    image: ravendb/ravendb:latest
    ports:
      - 8080:8080
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
    volumes:
      - C:\\Users\\dmarra\\Desktop\\FFMpegUIDemo\\RavenDbData:/data 

  ffmpegui.mvc:
    image: ${DOCKER_REGISTRY-}ffmpeguimvc
    #container_name: ffmpegui.mvc
    #command: ["./dockerize", "-wait", "tcp://ffmpeguisql:1433", "-timeout", "60s"]
    build:
      context: .
      dockerfile: FFMpegUI.Mvc/Dockerfile
    ports:
      - 57080:80
    environment:
      - ConnectionStrings__SqlDb=Server=ffmpeguisql;Database=FFMpegUI;User Id=sa;Password=yourStrong!Passw0rd;
      - QFileServerApiUrl=http://qfileserver
      - RavenDb__Urls=http://ffmpeguinosql:8080
      - RavenDb__Database=FFMpegUI
    depends_on:
      - ffmpeguisql
      - ffmpeguinosql

